// Generated by CoffeeScript 1.3.3
var canvas;

canvas = {
  canvasElement: null,
  ctx: null,
  width: 0,
  height: 0,
  isInitialized: function() {
    return canvas.ctx != null;
  },
  initialize: function(element) {
    canvas.canvasElement = element;
    canvas.ctx = element.getContext('2d');
    canvas.width = element.width;
    return canvas.height = element.height;
  },
  clear: function() {
    return canvas.ctx.clearRect(0, 0, canvas.width, canvas.height);
  },
  showSasai: function() {
    var ctx;
    ctx = canvas.ctx;
    ctx.save();
    ctx.font = 'italic 40pt Calibri';
    ctx.shadowColor = 'orange';
    ctx.shadowOffsetX = 3;
    ctx.shadowOffsetY = 3;
    ctx.fillText('SASAI LOLKA', ~~(canvas.width * 0.30), 100);
    ctx.font = 'italic 10pt Calibri';
    ctx.shadowColor = 'red';
    ctx.shadowOffsetX = 1;
    ctx.shadowOffsetY = 1;
    ctx.fillText('Click to replay', ~~(canvas.width * 0.50), 130);
    return ctx.restore();
  },
  drawYoba: function(params) {
    var R, ctx, fi, position, src;
    R = params.radius;
    fi = params.angle;
    src = params.src;
    ctx = canvas.ctx;
    position = params.position;
    ctx.save();
    ctx.translate(position - R, canvas.height - 2 * R);
    ctx.translate(R, R);
    ctx.rotate(fi);
    ctx.drawImage(src, -R, -R, 2 * R, 2 * R);
    return ctx.restore();
  }
};
