// Generated by CoffeeScript 1.3.3
var drawYobas;

drawYobas = function() {
  handler.stop();
  Yoba.removeYobas();
  if (!canvas.isInitialized()) {
    canvas.initialize(document.getElementById("yoba_track"));
  } else {
    canvas.clear();
  }
  new Yoba({
    radius: 50,
    position: 950
  });
  new Yoba({
    radius: 40,
    position: 400
  });
  new Yoba({
    radius: 60,
    position: 100
  });
  return handler.start();
};
