// Generated by CoffeeScript 1.4.0

Array.prototype.any = function() {
  var i, _i, _len;
  for (_i = 0, _len = this.length; _i < _len; _i++) {
    i = this[_i];
    if (i) {
      return true;
    }
  }
  return false;
};
