// Generated by CoffeeScript 1.3.3
var Yoba;

Yoba = (function() {
  var getMass, getSkin, registerYoba;

  function Yoba(params) {
    var defaultAngle, defaultRadius, defaultSpeed, yobaImage;
    yobaImage = new Image();
    yobaImage.src = getSkin();
    defaultRadius = 40;
    defaultSpeed = function() {
      return Math.floor(Math.random() * 25 + 5);
    };
    defaultAngle = 0;
    this.src = yobaImage;
    this.position = params.position;
    this.radius = params.radius || defaultRadius;
    this.speed = params.speed || defaultSpeed();
    this.angle = defaultAngle;
    this.mass = getMass(params.radius || defaultRadius);
    this.textDelay = 0;
    this.text = '';
    registerYoba(this);
  }

  registerYoba = function(self) {
    return Yoba.allYobas.push(self);
  };

  getMass = function(R) {
    var p;
    p = 0.0001;
    return Math.floor((4 / 3) * Math.PI * R * R * R * p);
  };

  getSkin = function() {
    var path, randomIndex, skins;
    path = "skins/";
    skins = ["1.png", "2.png", "3.png", "4.png"];
    randomIndex = Math.floor(Math.random() * skins.length);
    return path + skins[randomIndex];
  };

  Yoba.prototype.redraw = function() {
    return canvas.drawYoba({
      radius: this.radius,
      angle: this.angle,
      src: this.src,
      position: this.position
    });
  };

  Yoba.prototype.startSpeek = function() {
    this.textDelay = 10;
    return this.text = Yoba.getSwearword();
  };

  Yoba.prototype.continueSpeek = function() {
    if (this.textDelay > 0) {
      --this.textDelay;
      return canvas.ctx.fillText(this.text, this.position, 10);
    }
  };

  Yoba.scriptIntervalID = null;

  Yoba.allYobas = [];

  Yoba.removeYobas = function() {
    return this.allYobas = [];
  };

  Yoba.getSwearword = function() {
    var randomIndex, swearwords;
    swearwords = ["Sooqa", "Krysa", "LOL", "Tvoi mama ebal", "U tebya bugurt", "U vas popka prigorela", "Butthurt", "Lalka", "Sasai", "Pidor"];
    randomIndex = Math.floor(Math.random() * swearwords.length);
    return swearwords[randomIndex];
  };

  Yoba.stopScript = function() {
    clearInterval(Yoba.scriptIntervalID);
    return setTimeout(canvas.showSasai, 1000);
  };

  return Yoba;

})();
