// Generated by CoffeeScript 1.3.3
var Yoba;

Yoba = (function() {
  var defaultParams, getMass, getSkin;

  function Yoba(params) {
    var yobaImage;
    yobaImage = new Image();
    yobaImage.src = getSkin();
    YOBAS.push({
      src: yobaImage,
      position: params.position,
      radius: params.radius || defaultParams.radius,
      speed: params.speed || defaultParams.speed(),
      angle: defaultParams.angle,
      mass: getMass(params.radius || defaultParams.radius),
      textDelay: 0,
      text: ''
    });
  }

  defaultParams = {
    radius: 40,
    speed: function() {
      return Math.floor(Math.random() * 25 + 5);
    },
    angle: 0
  };

  getMass = function(R) {
    var p;
    p = 0.0001;
    return Math.floor((4 / 3) * Math.PI * R * R * R * p);
  };

  getSkin = function() {
    var path, randomIndex, skins;
    path = "skins/";
    skins = ["1.png", "2.png", "3.png", "4.png"];
    randomIndex = Math.floor(Math.random() * skins.length);
    return path + skins[randomIndex];
  };

  Yoba.canvasElement = null;

  Yoba.ctx = null;

  Yoba.scriptIntervalID = null;

  Yoba.getSwearword = function() {
    var randomIndex, swearwords;
    swearwords = ["Sooqa", "Krysa", "LOL", "Tvoi mama ebal", "U tebya bugurt", "U vas popka prigorela", "Butthurt", "Lalka", "Sasai", "Pidor"];
    randomIndex = Math.floor(Math.random() * swearwords.length);
    return swearwords[randomIndex];
  };

  return Yoba;

})();
